obj-m += i2c-psoc4-driver.o

i2c-psoc4-driver-objs := i2c-psoc4-main.o \
	i2c-psoc4-sysfs.o \
	i2c-psoc4-debugfs.o \
	i2c-psoc4-input.o \
	i2c-psoc4-irq.o \
	i2c-psoc4-dfu.o \
	psoc4-i2c.o \
	cybootloaderutils/cybtldr_api.o \
	cybootloaderutils/cybtldr_api2.o \
	cybootloaderutils/cybtldr_parse.o \
	cybootloaderutils/cybtldr_command.o
